name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:

  docker-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Check Weather Docker is there or not.
        run: docker version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # - name: Build and Push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     context: .
      #     tags: nishanthkp/httpapp:latest

      - name: Manual deploy
        run: |
          docker build -t aaiello7/flaskapp:${{ env.GITHUBRUNNERID }} .
          docker push aaiello7/flaskapp:${{ env.GITHUBRUNNERID }}

  dev-kube-deploy:
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps: 

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Manipulate the Kubernetes Image Version
        run: |
          cp kubetemplate/flaskapp-template.yml kubefiles/flaskapp-pod.yml
          sed -i "s/APPVERSION/${{ env.GITHUBRUNNERID }}/g" kubefiles/flaskapp-pod.yml

      - name: Commit and Push
        uses: devops-infra/action-commit-push@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Version Update